import type { Metadata } from "next";
import localFont from "next/font/local";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "./globals.css";
import { faFacebookF, faInstagram, faYoutube } from "@fortawesome/free-brands-svg-icons";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[1440px] mx-auto`}
      >
        <div className="root-layout">
          {/* Header */}
          <div className="header flex flex-row justify-between bg-red-500 items-center">
            <div className="flex-1 logo">
              LOGO
            </div>
            <div className="flex flex-row flex-1 justify-evenly gap-x-5 items-center">
              {/* Header links */}
              <div>
                Photography
              </div>
              <div>
                Films
              </div>
              <div>
                Contact Us
              </div>
              {/* Social media icons */}
              <FontAwesomeIcon icon={faFacebookF} />
              <FontAwesomeIcon icon={faInstagram} />
              <FontAwesomeIcon icon={faYoutube} />
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
